apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvix.fullname" . }}-secret
type: Opaque
stringData:
  SUPABASE_URL: {{ .Values.env.SUPABASE_URL | quote }}
  SUPABASE_KEY: {{ .Values.env.SUPABASE_KEY | quote }}
